version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: lucky
      POSTGRES_PASSWORD: "12345"
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql